apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: horizontal-pod
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: k8s-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
